sudo: required
services:
  - docker

before_install:
  - docker build -t larstijssen/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true larstijssen/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "Docker-react"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-central-1-860811459136"
  bucket_path: "Docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"

language: generic
